export const BNB = 'BNB'
export const BTC = 'BTC'
export const ETH = 'ETH'
export const TRX = 'TRX'
export const XRP = 'XRP'
export const FAV = 'FAV'
export const ADDFAV = 'ADDFAV'
export const INIT = 'INIT'
export const SEARCH = 'SEARCH'

export const SDT = 'SDT'
export const TUSD = 'TUSD'
export const BUSD = 'BUSD'
export const ALLUSD = 'ALLUSD'
export const ALL = 'ALL'